/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClankyRouteImport } from './routes/clanky'
import { Route as HodnoceniRouteImport } from './routes/hodnoceni'
import { Route as KandidatiRouteImport } from './routes/kandidati'
import { Route as ProgramRouteImport } from './routes/program'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClankyRoute = ClankyRouteImport.update({
  id: '/clanky',
  path: '/clanky',
  getParentRoute: () => rootRouteImport,
} as any)
const HodnoceniRoute = HodnoceniRouteImport.update({
  id: '/hodnoceni',
  path: '/hodnoceni',
  getParentRoute: () => rootRouteImport,
} as any)
const KandidatiRoute = KandidatiRouteImport.update({
  id: '/kandidati',
  path: '/kandidati',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clanky': typeof ClankyRoute
  '/hodnoceni': typeof HodnoceniRoute
  '/kandidati': typeof KandidatiRoute
  '/program': typeof ProgramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clanky': typeof ClankyRoute
  '/hodnoceni': typeof HodnoceniRoute
  '/kandidati': typeof KandidatiRoute
  '/program': typeof ProgramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clanky': typeof ClankyRoute
  '/hodnoceni': typeof HodnoceniRoute
  '/kandidati': typeof KandidatiRoute
  '/program': typeof ProgramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clanky' | '/hodnoceni' | '/kandidati' | '/program'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clanky' | '/hodnoceni' | '/kandidati' | '/program'
  id: '__root__' | '/' | '/clanky' | '/hodnoceni' | '/kandidati' | '/program'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClankyRoute: typeof ClankyRoute
  HodnoceniRoute: typeof HodnoceniRoute
  KandidatiRoute: typeof KandidatiRoute
  ProgramRoute: typeof ProgramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clanky': {
      id: '/clanky'
      path: '/clanky'
      fullPath: '/clanky'
      preLoaderRoute: typeof ClankyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hodnoceni': {
      id: '/hodnoceni'
      path: '/hodnoceni'
      fullPath: '/hodnoceni'
      preLoaderRoute: typeof HodnoceniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kandidati': {
      id: '/kandidati'
      path: '/kandidati'
      fullPath: '/kandidati'
      preLoaderRoute: typeof KandidatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClankyRoute: ClankyRoute,
  HodnoceniRoute: HodnoceniRoute,
  KandidatiRoute: KandidatiRoute,
  ProgramRoute: ProgramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
