/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClankyRouteImport } from './routes/clanky'
import { Route as HodnoceniRouteImport } from './routes/hodnoceni'
import { Route as KandidatiRouteImport } from './routes/kandidati'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as KandidatiIndexRouteImport } from './routes/kandidati.index'
import { Route as KandidatiSlugRouteImport } from './routes/kandidati.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClankyRoute = ClankyRouteImport.update({
  id: '/clanky',
  path: '/clanky',
  getParentRoute: () => rootRouteImport,
} as any)
const HodnoceniRoute = HodnoceniRouteImport.update({
  id: '/hodnoceni',
  path: '/hodnoceni',
  getParentRoute: () => rootRouteImport,
} as any)
const KandidatiRoute = KandidatiRouteImport.update({
  id: '/kandidati',
  path: '/kandidati',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const KandidatiIndexRoute = KandidatiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KandidatiRoute,
} as any)
const KandidatiSlugRoute = KandidatiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KandidatiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clanky': typeof ClankyRoute
  '/hodnoceni': typeof HodnoceniRoute
  '/kandidati': typeof KandidatiRouteWithChildren
  '/program': typeof ProgramRoute
  '/kandidati/$slug': typeof KandidatiSlugRoute
  '/kandidati/': typeof KandidatiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clanky': typeof ClankyRoute
  '/hodnoceni': typeof HodnoceniRoute
  '/program': typeof ProgramRoute
  '/kandidati/$slug': typeof KandidatiSlugRoute
  '/kandidati': typeof KandidatiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clanky': typeof ClankyRoute
  '/hodnoceni': typeof HodnoceniRoute
  '/kandidati': typeof KandidatiRouteWithChildren
  '/program': typeof ProgramRoute
  '/kandidati/$slug': typeof KandidatiSlugRoute
  '/kandidati/': typeof KandidatiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clanky'
    | '/hodnoceni'
    | '/kandidati'
    | '/program'
    | '/kandidati/$slug'
    | '/kandidati/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clanky'
    | '/hodnoceni'
    | '/program'
    | '/kandidati/$slug'
    | '/kandidati'
  id:
    | '__root__'
    | '/'
    | '/clanky'
    | '/hodnoceni'
    | '/kandidati'
    | '/program'
    | '/kandidati/$slug'
    | '/kandidati/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClankyRoute: typeof ClankyRoute
  HodnoceniRoute: typeof HodnoceniRoute
  KandidatiRoute: typeof KandidatiRouteWithChildren
  ProgramRoute: typeof ProgramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clanky': {
      id: '/clanky'
      path: '/clanky'
      fullPath: '/clanky'
      preLoaderRoute: typeof ClankyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hodnoceni': {
      id: '/hodnoceni'
      path: '/hodnoceni'
      fullPath: '/hodnoceni'
      preLoaderRoute: typeof HodnoceniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kandidati': {
      id: '/kandidati'
      path: '/kandidati'
      fullPath: '/kandidati'
      preLoaderRoute: typeof KandidatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kandidati/': {
      id: '/kandidati/'
      path: '/'
      fullPath: '/kandidati/'
      preLoaderRoute: typeof KandidatiIndexRouteImport
      parentRoute: typeof KandidatiRoute
    }
    '/kandidati/$slug': {
      id: '/kandidati/$slug'
      path: '/$slug'
      fullPath: '/kandidati/$slug'
      preLoaderRoute: typeof KandidatiSlugRouteImport
      parentRoute: typeof KandidatiRoute
    }
  }
}

interface KandidatiRouteChildren {
  KandidatiSlugRoute: typeof KandidatiSlugRoute
  KandidatiIndexRoute: typeof KandidatiIndexRoute
}

const KandidatiRouteChildren: KandidatiRouteChildren = {
  KandidatiSlugRoute: KandidatiSlugRoute,
  KandidatiIndexRoute: KandidatiIndexRoute,
}

const KandidatiRouteWithChildren = KandidatiRoute._addFileChildren(
  KandidatiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClankyRoute: ClankyRoute,
  HodnoceniRoute: HodnoceniRoute,
  KandidatiRoute: KandidatiRouteWithChildren,
  ProgramRoute: ProgramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
