/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClankyRouteImport } from './routes/clanky'
import { Route as HodnoceniRouteImport } from './routes/hodnoceni'
import { Route as KandidatiRouteImport } from './routes/kandidati'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as ClankyIndexRouteImport } from './routes/clanky.index'
import { Route as ClankySlugRouteImport } from './routes/clanky.$slug'
import { Route as KandidatiIndexRouteImport } from './routes/kandidati.index'
import { Route as KandidatiSlugRouteImport } from './routes/kandidati.$slug'
import { Route as ProgramIndexRouteImport } from './routes/program.index'
import { Route as ProgramSlugRouteImport } from './routes/program.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClankyRoute = ClankyRouteImport.update({
  id: '/clanky',
  path: '/clanky',
  getParentRoute: () => rootRouteImport,
} as any)
const HodnoceniRoute = HodnoceniRouteImport.update({
  id: '/hodnoceni',
  path: '/hodnoceni',
  getParentRoute: () => rootRouteImport,
} as any)
const KandidatiRoute = KandidatiRouteImport.update({
  id: '/kandidati',
  path: '/kandidati',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const ClankyIndexRoute = ClankyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClankyRoute,
} as any)
const ClankySlugRoute = ClankySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ClankyRoute,
} as any)
const KandidatiIndexRoute = KandidatiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KandidatiRoute,
} as any)
const KandidatiSlugRoute = KandidatiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KandidatiRoute,
} as any)
const ProgramIndexRoute = ProgramIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramRoute,
} as any)
const ProgramSlugRoute = ProgramSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clanky': typeof ClankyRouteWithChildren
  '/hodnoceni': typeof HodnoceniRoute
  '/kandidati': typeof KandidatiRouteWithChildren
  '/program': typeof ProgramRouteWithChildren
  '/clanky/$slug': typeof ClankySlugRoute
  '/kandidati/$slug': typeof KandidatiSlugRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/clanky/': typeof ClankyIndexRoute
  '/kandidati/': typeof KandidatiIndexRoute
  '/program/': typeof ProgramIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hodnoceni': typeof HodnoceniRoute
  '/clanky/$slug': typeof ClankySlugRoute
  '/kandidati/$slug': typeof KandidatiSlugRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/clanky': typeof ClankyIndexRoute
  '/kandidati': typeof KandidatiIndexRoute
  '/program': typeof ProgramIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clanky': typeof ClankyRouteWithChildren
  '/hodnoceni': typeof HodnoceniRoute
  '/kandidati': typeof KandidatiRouteWithChildren
  '/program': typeof ProgramRouteWithChildren
  '/clanky/$slug': typeof ClankySlugRoute
  '/kandidati/$slug': typeof KandidatiSlugRoute
  '/program/$slug': typeof ProgramSlugRoute
  '/clanky/': typeof ClankyIndexRoute
  '/kandidati/': typeof KandidatiIndexRoute
  '/program/': typeof ProgramIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clanky'
    | '/hodnoceni'
    | '/kandidati'
    | '/program'
    | '/clanky/$slug'
    | '/kandidati/$slug'
    | '/program/$slug'
    | '/clanky/'
    | '/kandidati/'
    | '/program/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hodnoceni'
    | '/clanky/$slug'
    | '/kandidati/$slug'
    | '/program/$slug'
    | '/clanky'
    | '/kandidati'
    | '/program'
  id:
    | '__root__'
    | '/'
    | '/clanky'
    | '/hodnoceni'
    | '/kandidati'
    | '/program'
    | '/clanky/$slug'
    | '/kandidati/$slug'
    | '/program/$slug'
    | '/clanky/'
    | '/kandidati/'
    | '/program/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClankyRoute: typeof ClankyRouteWithChildren
  HodnoceniRoute: typeof HodnoceniRoute
  KandidatiRoute: typeof KandidatiRouteWithChildren
  ProgramRoute: typeof ProgramRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clanky': {
      id: '/clanky'
      path: '/clanky'
      fullPath: '/clanky'
      preLoaderRoute: typeof ClankyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hodnoceni': {
      id: '/hodnoceni'
      path: '/hodnoceni'
      fullPath: '/hodnoceni'
      preLoaderRoute: typeof HodnoceniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kandidati': {
      id: '/kandidati'
      path: '/kandidati'
      fullPath: '/kandidati'
      preLoaderRoute: typeof KandidatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clanky/': {
      id: '/clanky/'
      path: '/'
      fullPath: '/clanky/'
      preLoaderRoute: typeof ClankyIndexRouteImport
      parentRoute: typeof ClankyRoute
    }
    '/clanky/$slug': {
      id: '/clanky/$slug'
      path: '/$slug'
      fullPath: '/clanky/$slug'
      preLoaderRoute: typeof ClankySlugRouteImport
      parentRoute: typeof ClankyRoute
    }
    '/kandidati/': {
      id: '/kandidati/'
      path: '/'
      fullPath: '/kandidati/'
      preLoaderRoute: typeof KandidatiIndexRouteImport
      parentRoute: typeof KandidatiRoute
    }
    '/kandidati/$slug': {
      id: '/kandidati/$slug'
      path: '/$slug'
      fullPath: '/kandidati/$slug'
      preLoaderRoute: typeof KandidatiSlugRouteImport
      parentRoute: typeof KandidatiRoute
    }
    '/program/': {
      id: '/program/'
      path: '/'
      fullPath: '/program/'
      preLoaderRoute: typeof ProgramIndexRouteImport
      parentRoute: typeof ProgramRoute
    }
    '/program/$slug': {
      id: '/program/$slug'
      path: '/$slug'
      fullPath: '/program/$slug'
      preLoaderRoute: typeof ProgramSlugRouteImport
      parentRoute: typeof ProgramRoute
    }
  }
}

interface ClankyRouteChildren {
  ClankySlugRoute: typeof ClankySlugRoute
  ClankyIndexRoute: typeof ClankyIndexRoute
}

const ClankyRouteChildren: ClankyRouteChildren = {
  ClankySlugRoute: ClankySlugRoute,
  ClankyIndexRoute: ClankyIndexRoute,
}

const ClankyRouteWithChildren =
  ClankyRoute._addFileChildren(ClankyRouteChildren)

interface KandidatiRouteChildren {
  KandidatiSlugRoute: typeof KandidatiSlugRoute
  KandidatiIndexRoute: typeof KandidatiIndexRoute
}

const KandidatiRouteChildren: KandidatiRouteChildren = {
  KandidatiSlugRoute: KandidatiSlugRoute,
  KandidatiIndexRoute: KandidatiIndexRoute,
}

const KandidatiRouteWithChildren = KandidatiRoute._addFileChildren(
  KandidatiRouteChildren,
)

interface ProgramRouteChildren {
  ProgramSlugRoute: typeof ProgramSlugRoute
  ProgramIndexRoute: typeof ProgramIndexRoute
}

const ProgramRouteChildren: ProgramRouteChildren = {
  ProgramSlugRoute: ProgramSlugRoute,
  ProgramIndexRoute: ProgramIndexRoute,
}

const ProgramRouteWithChildren =
  ProgramRoute._addFileChildren(ProgramRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClankyRoute: ClankyRouteWithChildren,
  HodnoceniRoute: HodnoceniRoute,
  KandidatiRoute: KandidatiRouteWithChildren,
  ProgramRoute: ProgramRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
